language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"
    - "3.4"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install argparse unittest2; fi
    - python setup.py install --quiet
    - pip install --quiet pytest-cov
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - echo -e "[ui]\nusername = Your Name <your@email.com>" > ~/.hgrc
    - bzr whoami "Your Name <you@example.com>"

script:
    - nosetests --with-coverage --cover-package=pep8radius

after_success:
    - pip install --quiet coveralls
    - coveralls
